name: Python Package using Conda

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          use-mamba: false  # Use classic conda solver

      - name: Initialize Conda
        run: conda init bash

      - name: Reload Shell
        run: source ~/.bashrc

      - name: Create Environment
        run: conda env create -f environment.yml

      - name: Activate Environment
        run: conda activate ai-comment-classifier

      - name: Run Tests
        run: pytest
