name: Python Package using Conda

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          use-mamba: false  # Disable mamba
      - name: Set classic solver
        run: conda config --set solver classic
      - name: Create Environment
        run: conda env create -f environment.yml
      - name: Activate Environment
        run: conda activate ai-comment-classifier
